pipeline_name: PaddleOCR-VL
batch_size: 64
use_doc_preprocessor: false
SubPipelines:
  LayoutDetection:
    module_name: PP-DocLayoutV2
    batch_size: 8
  DocVLRec:
    module_name: PaddleOCR-VL-0.9B
    batch_size: 4096
    backend: vllm-server
    server_url: http://localhost:8080/v1
